# Supported funding platforms

github: [jurgen-paul]                              # Up to 4 GitHub Sponsors-enabled usernames
patreon: jurgenpaul                                # Your Patreon username
open_collective: tactical-legends                  # Your Open Collective username
ko_fi: jurgenpaul                                  # Your Ko-fi username
tidelift: npm/tactical-legends                     # Example Tidelift package name
community_bridge: tactical-legends                 # Example Community Bridge project name
liberapay: jurgenpaul                              # Your Liberapay username
issuehunt: tactical-legends                        # Your IssueHunt username
lfx_crowdfunding: tactical-legends                 # Example LFX Crowdfunding project name
polar: jurgenpaul                                  # Your Polar username
buy_me_a_coffee: jurgenpaul                        # Your Buy Me a Coffee username
thanks_dev: jurgenpaul                             # Your thanks.dev username
custom: ['https://paypal.me/jurgenpaul', 'https://jurgenpaul.com/donate'] # Up to 4 custom URLs

# Example Stripe Integration (move to JS/TS file, not YAML)
# const stripe = require('stripe')('your_secret_key'); // Replace with your Stripe secret key
# async function createSubscription(customerId, priceId) {
#   try {
#     const subscription = await stripe.subscriptions.create({
#       customer: customerId,
#       items: [{ price: priceId }],
#       metadata: { organization_id: 'org_6RsNhnGbSQ3s7rFPAoYfQjA' },
#     });
#     console.log('Subscription created:', subscription.id);
#   } catch (error) {
#     console.error('Error creating subscription:', error);
#   }
# }
# // Example usage
# const customerId = 'cus_xxxxxxxxxxxxx'; // Replace with your customer ID
# const priceId = 'price_xxxxxxxxxxxxx'; // Replace with your price ID
# createSubscription(customerId, priceId);
